### ISSUE TITLE
obtainedFrom should be an array

### ISSUE THREAD

**Issue by antriver** [sungyeonu/animal-crossing-scraper#10]
Many of the items can be obtained from multiple sources (see https://animalcrossing.fandom.com/wiki/DIY_recipes/Miscellaneous) so the obtainedFrom property should be an array of strings rather than a single string

**Comment by sungyeonu** [comment]
I just pushed the code, wanna have a look before I close this issue?

**Comment by antriver** [comment]
@sungyeonu Looks good now!
I was working on a branch to fix loading the "DIY Recipes / Others" page but I see you've fixed that too :)

**Comment by sungyeonu** [comment]
Wonderful. Closing the issue now!
