### ISSUE TITLE
Critter object key error

### ISSUE THREAD

**Issue by feralheart** [sungyeonu/animal-crossing-scraper#11]
I saw that the the critter objects has dashes as the monthKey.
`"seasons-northern-hemisphere"`
Can you change it to underscores? Because some programming languages has problems when array/object key has dash in it.

**Comment by sungyeonu** [comment]
Yea, I can definitely do that. Or would you prefer camelCase like imageLinks? like SeasonsNorthernHemisphere?

**Comment by feralheart** [comment]
Yes it's even better :)
