### ISSUE TITLE
Feature request: Scrape the villager's main page for additional villager info

### ISSUE THREAD

**Issue by feralheart** [sungyeonu/animal-crossing-scraper#19]
Suggested aditional information:
- The main image 
- Caption under the main image
- Gender (Separated from the personality)
- Initial clothes
- Skill
- Goal
- Coffee
- Favorite song
- Style
- The text from the Appearance section
- The text from the House section
- The text from the Trivia section

**Comment by sungyeonu** [comment]
Cool Cool I like this. I assume this file will be the biggest JSON yet!

**Comment by sungyeonu** [comment]
scraped everything but appearance/house/trivia section

**Comment by feralheart** [comment]
Thank you
Can you also scrape the villager's main image?

**Comment by sungyeonu** [comment]
Yes of course.
So each villager has two images: one on the villagers list page, and one on their individual wiki page. Should they be in one list that will contain the URLs to both image or be individually named like "main_image_url" and "side_image_url"? Do you have ideas for better names?

**Comment by feralheart** [comment]
I think separated keys would be the best.
For example "main_image_url" and "photo_gift_url" (because the image from the table is the same what they can give you when you have high friendship with them)
