### ISSUE TITLE
Update request: Use the original image link without the downscale tag

### ISSUE THREAD

**Issue by feralheart** [sungyeonu/animal-crossing-scraper#20]
In some pages there's a downscale query in the image url, for example on DIY pages materials section:
`https://vignette.wikia.nocookie.net/animalcrossing/images/d/d4/NH-acorn_icon.png/revision/latest/scale-to-width-down/18?cb=20200407141759`
There the part `/scale-to-width-down/18` downscales the acorn icon to a small 18x18 icon. If you skip that part of the URL you'll got the original image.

As I saw this tag is used on the DIY page at the materials part and on the villagers page at the villager images, but maybe they're used at other places at well.

**Comment by sungyeonu** [comment]
Great catch!
