### ISSUE TITLE
Bug Report: DIY items with broken imageLink

### ISSUE THREAD

**Issue by feralheart** [sungyeonu/animal-crossing-scraper#21]
I tried several images in the DIY jsons, but for every try I got the "broken image" image as the result
For example this is the "Ironwood DIY Workbench"'s image: `https://vignette.wikia.nocookie.net/animalcrossing/images/2/2e/NH-Ironwood_DIY_workbench.png/revision/latest?cb=20200329061925`

**Comment by sungyeonu** [comment]
Working on this asap

**Comment by sungyeonu** [comment]
The wiki changed the links to the images. I wish they were more consistent with their contents :P
