### ISSUE TITLE
Feature request: Scrape flowers

### ISSUE THREAD

**Issue by Cabskee** [sungyeonu/animal-crossing-scraper#24]
Could you scrape flowers, colors, breeding data, etc.?

**Comment by sungyeonu** [comment]
Yea I can do that. 

I found some scrapable link at https://animalcrossing.fandom.com/wiki/Flower/New_Horizons_mechanics#Northern%20Hemisphere, will work on this when I'm done with scrape clothing

![image](https://user-images.githubusercontent.com/47223114/82005036-5bbf0d00-9632-11ea-8415-c47b06bdd3da.png)

**Comment by sungyeonu** [comment]
Scraped flowers availability and genetics for now. simple and advaned hybridization coming tmrw

**Comment by sungyeonu** [comment]
Finished scraping! If you have any suggestions for how json should be named or structured, PLEASE let me know. I have 0 knowledge on biology and this one was confusing.
