### ISSUE TITLE
Missing data on villlagers

### ISSUE THREAD

**Issue by mathewthe2** [sungyeonu/animal-crossing-scraper#38]
- home_request: ['Admiral', 'Audie', 'Bea', 'Billy', 'Biskit', 'Boots', 'Boris', 'Boyd', 'Buzz', 'Candi', 'Cashmere', 'Chester', 'Claudia', 'Cleo', 'Cyd', 'Dobie', 'Dom', 'Ellie', 'Gonzo', 'Hopkins', 'Hornsby', 'Huck', 'Ike', 'Jacob', 'Judy', 'Julia', 'June', 'Ketchup', 'Leopold', 'Lily', 'Megan', 'Mott', 'Murphy', 'Nibbles', 'Norma', 'Olive', 'Paolo', 'Peewee', 'Piper', 'Plucky', 'Raddle', 'Raymond', 'Reneigh', 'Rex', 'Rory', 'Sandy', 'Shep', 'Sherb', 'Snooty', 'Spike', 'Sprocket', 'Stella', 'Stu', 'Sylvana', 'Tad', 'Tammi', 'Tank', 'Tasha', 'Tybalt', 'Ursala', 'Vivian', 'Wade', 'Weber', 'Zucker']

- goal: ['Biskit', 'Dobie', 'Lily']

- skill: ['Biskit', 'Dobie', 'Lily']

- coffee: ['Biskit', 'Dobie', 'Lily']

- initial_clothes: ['Dobie', 'Lily']

- initial_phrase: ['Dobie']

- favorite_song: ['Biskit', 'Dobie', 'Lily', 'Louie', 'Paolo', 'Spike']

- style: ['Admiral', 'Bea', 'Billy', 'Biskit', 'Boots', 'Boris', 'Boyd', 'Buzz', 'Carrie', 'Cashmere', 'Claude', 'Cleo', 'Dobie', 'Ellie', 'Gonzo', 'Hornsby', 'Huck', 'Jacob', 'Julia', 'June', 'Ketchup', 'Leopold', 'Lily', 'Maddie', 'Maggie', 'Murphy', 'Norma', 'Paolo', 'Piper', 'Plucky', 'Raddle', 'Sandy', 'Sherb', 'Spike', 'Sprocket', 'Stella', 'Stu', 'Sylvana', 'Tad', 'Tasha', 'Tybalt', 'Ursala', 'Wade', 'Weber']

- appearance: ['Biskit', 'Dobie', 'Lily']

- birthday: ['Dobie']

- species: ['Dobie']

Villagers such as Dom and Judy with field values = null are not included.

**Comment by sungyeonu** [comment]
Will fix this and other issues regarding villagers tonight!

**Comment by mathewthe2** [comment]
Thank you. Also, the birthdays of Samson, Tia, Pecan, Plucky, Vivian is in "MMMM D" format instead of "MMMM Do" like the other villagers.

**Comment by sungyeonu** [comment]
Will date format of like September 11th be okay?

**Comment by mathewthe2** [comment]
Yes. That is "MMMM Do". I think one format for all the birthdays is better. (The format on the animal crossing wiki is inconsistent)

**Comment by sungyeonu** [comment]
Fixed these issues. Wanna have a look before I close out the issue?

**Comment by mathewthe2** [comment]
Looks good to me. Although now the information of astrological signs of the villagers that were originally in their birthday are gone.

**Comment by sungyeonu** [comment]
Perfect. I'll create a separate issue for the astrological signs and close this issue.
