### ISSUE TITLE
Modification request: Separate the critter "Active Hours"

### ISSUE THREAD

**Issue by feralheart** [sungyeonu/animal-crossing-scraper#41]
There are several critters with two active time ranges and it shared in the same string.
For example: '4 AM - 8 AM & 4 PM - 7 PM'
Can you separate the two time ranges as separate strings?

**Comment by sungyeonu** [comment]
Please refer to the PR for details! 

In addition, do you think changing all keys in critters (or other jsons) to have underscore instead of spaces a good idea? And have "name" attribute for the actual name instead.

**Comment by feralheart** [comment]
Yes it would be better if the keys would have underscores instead of spaces
