### ISSUE TITLE
Add full-size-image, catch-phrase, museum-phrase to fish and bugs?

### ISSUE THREAD

**Issue by mathewthe2** [sungyeonu/animal-crossing-scraper#43]
Example: https://animalcrossing.fandom.com/wiki/Bitterling

- catch-phrase: "I caught a bitterling! It's mad at me, but only a little."

- museum-phrase: "Bitterlings hide their eggs inside large bivalves—like clams—where the young can stay safe until grown. The bitterling isn't being sneaky. No, their young help keep the bivalve healthy by eating invading parasites! It's a wonderful bit of evolutionary deal making, don't you think? Each one keeping the other safe... Though eating parasites does not sound like a happy childhood... Is that why the fish is so bitter?"

- full-size-image: https://vignette.wikia.nocookie.net/animalcrossing/images/e/e9/Nh-bitterling.jpg/revision/latest?cb=20200331062501

acnhapi.com uses _image_ and _icon_ to seperate the two images. Currently this repo only scrapes the icon. Also, the full-size-image on animal crossing.fandom has a background color while acnhapi.com offers the full-size-image like https://acnhapi.com/v1/images/fish/1 without background colors.

**Comment by sungyeonu** [comment]
A lot of the wiki were in inconsistent format, I went on the pages manually and found contents :/

**Comment by mathewthe2** [comment]
I don't think it's a terrible idea to directly 'scrape' from acnhapi.com

**Comment by sungyeonu** [comment]
you are right, the images are much cleaner.

museum_phrase and catch_phrase are still difficult to scrape from the wiki. I'll just scrape from acnhapi instead

**Comment by sungyeonu** [comment]
I have finals exams and projects this week, I will make sure to update the code this weekend
