### ISSUE TITLE
Feature request: Scraping of villagers

### ISSUE THREAD

**Issue by feralheart** [sungyeonu/animal-crossing-scraper#5]
Can you add a JSON for the villager data?

**Comment by sungyeonu** [comment]
I found a link for it:
https://animalcrossing.fandom.com/wiki/Villager_list_(New_Horizons)

It would get Name, Image, Personality, Species, Birthday, and Catch Phrase. 

Thanks for the request!

**Comment by sungyeonu** [comment]
See https://github.com/sungyeonu/animal-crossing-scraper/blob/master/data/villagers.json

**Comment by feralheart** [comment]
Thank you
