### ISSUE TITLE
Feature request: Add hemisphere based critter data

### ISSUE THREAD

**Issue by feralheart** [sungyeonu/animal-crossing-scraper#6]
Can you add both hemispheres to the `fish` and to the `bug` data?

**Comment by sungyeonu** [comment]
Yup, I think it will look like
{"bitterling":
  {"price": 900}
  {"northern-hemisphere":
    {"jan": true}
    .
    .
    .
  {"southern-hemisphere":
    {"jan": false}
    .
    .
    .


what do u think?

**Comment by feralheart** [comment]
I like it :)

**Comment by feralheart** [comment]
I like it

**Comment by feralheart** [comment]
I like it :)

**Comment by sungyeonu** [comment]
Done! Please go have a look. I also improved the structure of the json.

- https://github.com/sungyeonu/animal-crossing-scraper/blob/master/data/bugs.json
- https://github.com/sungyeonu/animal-crossing-scraper/blob/master/data/fish.json

**Comment by feralheart** [comment]
Thank you :)
