### ISSUE TITLE
Bug: Missing villager images

### ISSUE THREAD

**Issue by feralheart** [sungyeonu/animal-crossing-scraper#7]
For Spork and Jacob the image url is missing.
There is only `/wiki/Crackle` and `/wiki/Jacob` in the json as the url.

**Comment by sungyeonu** [comment]
Recently wiki updated their format (for the 1000th time) and data that were already completed are now incomplete. Working on the fix, big thanks for pointing out the mistakes.

**Comment by sungyeonu** [comment]
Fixed, please take a look at this one as well. I also changed the structure of the JSON.
