### ISSUE TITLE
Create a separate completed_fossils.json file

### ISSUE THREAD

**Issue by sungyeonu** [sungyeonu/animal-crossing-scraper#8]
Then nest the parts in it

**Comment by antriver** [comment]
I disagree. Having the each part listed separately makes sense because each part is an individual item to collect. However, having a separate completed_fossils.json file (or something that) which lists each fossil and all its parts would be a good idea.

**Comment by sungyeonu** [comment]
You are right. I was considering if this was worth, but now reading your comment it makes sense to leave as it is. Your input is brilliant, I am going to update the issue to reflect it.
